version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/server-nest"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
